build:
  ami:
    debug: true
    image: 192.168.12.212:5000/plataforma/packer-buildpack:master-00d91d1-2
    environment:
      OAS_REPO: $$OAS_REPO
      OAS_VPC: $$OAS_VPC
      OAS_SUBNET: $$OAS_SUBNET
      OAS_FORCE_CLEANUP: "false"
      AWS_ACCESS_KEY_ID: $$AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $$AWS_SECRET_ACCESS_KEY
      AWS_DEFAULT_OUTPUT: "json"
      AWS_DEFAULT_REGION: "us-east-1"
      OAS_EXTERNAL_REF: $$BRANCH-$${COMMIT:0:7}-$$BUILD_NUMBER
    commands:
      - ./ami.sh

publish:
  docker:
    registry: 192.168.12.212:5000
    repo: plataforma/condor-estudiantes-ami
    tag:
      - latest
      - $$BRANCH-$${COMMIT:0:7}-$$BUILD_NUMBER
    file: Dockerfile
    insecure: true
    load: docker/image.tar
    save:
      destination: docker/image.tar
      tag: latest
    storage_driver: overlay

cache:
  mount:
    - docker/image.tar

notify:
  webhook:
    urls:
      - "https://api.telegram.org/bot$$TELEGRAM_BOT_KEY/sendMessage"
    content_type: application/json
    template: >
      {
        "chat_id": "-130629599",
        "parse_mode": "Markdown",
        "text": "[{{uppercase build.status}}]({{build.link_url}}) {{repo.full_name}}:{{build.branch}}-{{truncate build.commit 7}}-{{build.number}} {{build.author}} authored \"{{truncate build.message 25}}\"... took {{duration build.started_at build.finished_at}}"
      }
