build:
  image: ci.192.168.12.212.xip.io:5000/oas/packer-buildpack:master-7645ec5-13
  environment:
    OAS_REPO: oas-repo
    OAS_VPC: vpc-422eda25
    OAS_SUBNET: subnet-b46b0bec
    AWS_ACCESS_KEY_ID: $$AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $$AWS_SECRET_ACCESS_KEY
  commands:
  - ./run.sh
  notify:
    webhook:
      debug: true
      urls:
      - "https://api.telegram.org/bot$$TELEGRAM_BOT_KEY/sendMessage"
      content_type: application/json
      template: >
        {
          "chat_id": "-29158603",
          "text": "{{repo.full_name}} $${BRANCH} $${COMMIT:0:7} $${BUILD_NUMBER} {{build.status}}"
        }
