build:
  build_ami:
    image: 10.20.0.126:5000/plataforma/packer-buildpack:develop-a7b4431-2
    environment:
      OAS_STACKS_NAMES: "condorB$$BRANCH"
      OAS_FORCE_CLEANUP: false
      AWS_ACCESS_KEY_ID: $$AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $$AWS_SECRET_ACCESS_KEY
      AWS_DEFAULT_OUTPUT: json
      AWS_DEFAULT_REGION: us-east-1
      AWS_SPOT_PRICE_BID: 0.020
      OAS_EXTERNAL_REF: $$BRANCH-$${COMMIT:0:7}-$$BUILD_NUMBER
      PACKER_MOCK_CREATION: false
      PACKER_INSTANCE_TYPE: m3.medium
    commands:
      - ./ci.sh

publish:
  docker:
    registry: 10.20.0.126:5000
    repo: plataforma/condor-image
    tag:
      - latest
      - $$BRANCH-$${COMMIT:0:7}-$$BUILD_NUMBER
    file: Dockerfile
    insecure: true
    storage_driver: overlay

cache:
  mount:
    - /drone/docker
